<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictsSeeder extends Seeder
{
    public function run(): void
    {
        $districts = $this->getDistrictsData();
        DB::table('districts')->insert($districts);
    }

    public function getDistrictsData(): array
    {
        return [
            ['id' => 1, 'zone_id' => 1, 'name' => 'Al Amal', 'name_ar' => 'حي العمل', 'price' => 5],
            ['id' => 2, 'zone_id' => 1, 'name' => 'Al Namudhajiyah', 'name_ar' => 'حي النموذجية', 'price' => 5],
            ['id' => 3, 'zone_id' => 1, 'name' => 'Al Jarradiyah', 'name_ar' => 'حي الجرادية', 'price' => 5],
            ['id' => 4, 'zone_id' => 1, 'name' => 'Al Sinaiyah', 'name_ar' => 'حي الصناعية', 'price' => 5],
            ['id' => 5, 'zone_id' => 1, 'name' => 'Manfuha Al Jadidah', 'name_ar' => 'حي منفوحة الجديدة', 'price' => 5],
            ['id' => 6, 'zone_id' => 1, 'name' => 'Al Fakhiriyah', 'name_ar' => 'حي الفاخرية', 'price' => 5],
            ['id' => 7, 'zone_id' => 1, 'name' => 'Al Dirah', 'name_ar' => 'حي الديرة', 'price' => 5],
            ['id' => 8, 'zone_id' => 1, 'name' => 'East Umm Al Hamam', 'name_ar' => 'حي ام الحمام الشرقي', 'price' => 5],
            ['id' => 9, 'zone_id' => 1, 'name' => 'Al Sharafiyah', 'name_ar' => 'حي الشرفية', 'price' => 5],
            ['id' => 10, 'zone_id' => 1, 'name' => 'Al Hada', 'name_ar' => 'حي الهدا', 'price' => 5],
            ['id' => 11, 'zone_id' => 1, 'name' => 'North Mathar', 'name_ar' => 'حي المعذر الشمالي', 'price' => 5],
            ['id' => 12, 'zone_id' => 1, 'name' => 'West Umm Al Hamam', 'name_ar' => 'حي ام الحمام الغربي', 'price' => 5],
            ['id' => 13, 'zone_id' => 1, 'name' => 'Ar Rahmaniyah', 'name_ar' => 'حي الرحمانية', 'price' => 5],
            ['id' => 14, 'zone_id' => 1, 'name' => 'Laban', 'name_ar' => 'حي لبن', 'price' => 5],
            ['id' => 15, 'zone_id' => 1, 'name' => 'Ar Rafiah', 'name_ar' => 'حي الرفيعة', 'price' => 5],
            ['id' => 16, 'zone_id' => 1, 'name' => 'Al Shohda', 'name_ar' => 'حي الشهداء', 'price' => 5],
            ['id' => 17, 'zone_id' => 1, 'name' => 'King Fahd', 'name_ar' => 'حي الملك فهد', 'price' => 5],
            ['id' => 18, 'zone_id' => 1, 'name' => 'Al Suwaidi', 'name_ar' => 'حي السويدي', 'price' => 5],
            ['id' => 19, 'zone_id' => 1, 'name' => 'Al Hazm', 'name_ar' => 'حي الحزم', 'price' => 5],
            ['id' => 20, 'zone_id' => 1, 'name' => 'Utayqah', 'name_ar' => 'حي عتيقة', 'price' => 5],
            ['id' => 21, 'zone_id' => 1, 'name' => 'Al Murabba', 'name_ar' => 'حي المربع', 'price' => 5],
            ['id' => 22, 'zone_id' => 1, 'name' => 'Al Falah', 'name_ar' => 'حي الفلاح', 'price' => 5],
            ['id' => 23, 'zone_id' => 1, 'name' => 'Al Nada', 'name_ar' => 'حي الندى', 'price' => 5],
            ['id' => 24, 'zone_id' => 1, 'name' => 'Al Mursalat', 'name_ar' => 'حي المرسلات', 'price' => 5],
            ['id' => 25, 'zone_id' => 1, 'name' => 'Al Nuzha', 'name_ar' => 'حي النزهة', 'price' => 5],
            ['id' => 26, 'zone_id' => 1, 'name' => 'Al Woroud', 'name_ar' => 'حي الورود', 'price' => 5],
            ['id' => 27, 'zone_id' => 1, 'name' => 'King Faisal', 'name_ar' => 'حي الملك فيصل', 'price' => 5],
            ['id' => 28, 'zone_id' => 1, 'name' => 'Al Aziziyah', 'name_ar' => 'حي العزيزية', 'price' => 5],
            ['id' => 29, 'zone_id' => 1, 'name' => 'Al Mansurah', 'name_ar' => 'حي المنصورة', 'price' => 5],
            ['id' => 30, 'zone_id' => 1, 'name' => 'Ghobairah', 'name_ar' => 'حي غبيرة', 'price' => 5],
            ['id' => 31, 'zone_id' => 1, 'name' => 'Al Farooq', 'name_ar' => 'حي الفاروق', 'price' => 5],
            ['id' => 32, 'zone_id' => 1, 'name' => 'Al Faisaliyah', 'name_ar' => 'حي الفيصلية', 'price' => 5],
            ['id' => 33, 'zone_id' => 1, 'name' => 'Al Khalidiyah', 'name_ar' => 'حي الخالدية', 'price' => 5],
            ['id' => 34, 'zone_id' => 1, 'name' => 'Al Jazeerah', 'name_ar' => 'حي الجزيرة', 'price' => 5],
            ['id' => 35, 'zone_id' => 1, 'name' => 'Al Saadah', 'name_ar' => 'حي السعادة', 'price' => 5],
            ['id' => 36, 'zone_id' => 1, 'name' => 'Al Nasiriyah', 'name_ar' => 'حي الناصرية', 'price' => 5],
            ['id' => 37, 'zone_id' => 1, 'name' => 'Al Manakh', 'name_ar' => 'حي المناخ', 'price' => 5],
            ['id' => 38, 'zone_id' => 1, 'name' => 'Al Difaa', 'name_ar' => 'حي الدفاع', 'price' => 5],
            ['id' => 39, 'zone_id' => 1, 'name' => 'Al Noor', 'name_ar' => 'حي النور', 'price' => 5],
            ['id' => 40, 'zone_id' => 1, 'name' => 'King Abdullah', 'name_ar' => 'حي الملك عبدالله', 'price' => 5],
            ['id' => 41, 'zone_id' => 1, 'name' => 'Al Wahah', 'name_ar' => 'حي الواحة', 'price' => 5],
            ['id' => 42, 'zone_id' => 1, 'name' => 'Salahuddin', 'name_ar' => 'حي صلاح الدين', 'price' => 5],
            ['id' => 43, 'zone_id' => 1, 'name' => 'King Abdulaziz', 'name_ar' => 'حي الملك عبدالعزيز', 'price' => 5],
            ['id' => 44, 'zone_id' => 1, 'name' => 'Al Wizarat', 'name_ar' => 'حي الوزارات', 'price' => 5],
            ['id' => 45, 'zone_id' => 1, 'name' => 'Skirinah', 'name_ar' => 'حي سكيرينة', 'price' => 5],
            ['id' => 46, 'zone_id' => 1, 'name' => 'Ar Rabwah', 'name_ar' => 'حي الربوة', 'price' => 5],
            ['id' => 47, 'zone_id' => 1, 'name' => 'Jareer', 'name_ar' => 'حي جرير', 'price' => 5],
            ['id' => 48, 'zone_id' => 1, 'name' => 'Al Mathar', 'name_ar' => 'حي المعذر', 'price' => 5],
            ['id' => 49, 'zone_id' => 1, 'name' => 'As Salhiyah', 'name_ar' => 'حي الصالحية', 'price' => 5],
            ['id' => 50, 'zone_id' => 1, 'name' => 'Al Malaz', 'name_ar' => 'حي الملز', 'price' => 5],
            ['id' => 51, 'zone_id' => 1, 'name' => 'Manfuhah', 'name_ar' => 'حي منفوحة', 'price' => 5],
            ['id' => 52, 'zone_id' => 1, 'name' => 'Olaishah', 'name_ar' => 'حي عليشة', 'price' => 5],
            ['id' => 53, 'zone_id' => 1, 'name' => 'Al Nahdah', 'name_ar' => 'حي النهضة', 'price' => 5],
            ['id' => 54, 'zone_id' => 1, 'name' => 'Al Khaleej', 'name_ar' => 'حي الخليج', 'price' => 5],
            ['id' => 55, 'zone_id' => 1, 'name' => 'Al Dhubbat', 'name_ar' => 'حي الضباط', 'price' => 5],
            ['id' => 56, 'zone_id' => 1, 'name' => 'West Suwaidi', 'name_ar' => 'حي السويدي الغربي', 'price' => 5],
            ['id' => 57, 'zone_id' => 1, 'name' => 'Dirab', 'name_ar' => 'حي ديراب', 'price' => 5],
            ['id' => 58, 'zone_id' => 1, 'name' => 'Ohod', 'name_ar' => 'حي احد', 'price' => 5],
            ['id' => 59, 'zone_id' => 1, 'name' => 'Namar', 'name_ar' => 'حي نمار', 'price' => 5],
            ['id' => 60, 'zone_id' => 1, 'name' => 'Al Shifa', 'name_ar' => 'حي الشفا', 'price' => 5],
            ['id' => 61, 'zone_id' => 1, 'name' => 'Al Muhammadiyah', 'name_ar' => 'حي المحمدية', 'price' => 5],
            ['id' => 62, 'zone_id' => 1, 'name' => 'Al Sulaimaniyah', 'name_ar' => 'حي السليمانية', 'price' => 5],
            ['id' => 63, 'zone_id' => 1, 'name' => 'Al Marwah', 'name_ar' => 'حي المروة', 'price' => 5],
            ['id' => 64, 'zone_id' => 1, 'name' => 'Okaz', 'name_ar' => 'حي عكاظ', 'price' => 5],
            ['id' => 65, 'zone_id' => 1, 'name' => 'Shubra', 'name_ar' => 'حي شبرا', 'price' => 5],
            ['id' => 66, 'zone_id' => 1, 'name' => 'Al Zahrah', 'name_ar' => 'حي الزهرة', 'price' => 5],
            ['id' => 67, 'zone_id' => 1, 'name' => 'Siyah', 'name_ar' => 'حي صياح', 'price' => 5],
            ['id' => 68, 'zone_id' => 1, 'name' => 'Sultanah', 'name_ar' => 'حي سلطانة', 'price' => 5],
            ['id' => 69, 'zone_id' => 1, 'name' => 'Al Yamamah', 'name_ar' => 'حي اليمامة', 'price' => 5],
            ['id' => 70, 'zone_id' => 1, 'name' => 'Al Badiah', 'name_ar' => 'حي البديعة', 'price' => 5],
            ['id' => 71, 'zone_id' => 1, 'name' => 'Al Masani', 'name_ar' => 'حي المصانع', 'price' => 5],
            ['id' => 72, 'zone_id' => 1, 'name' => 'Al Qadisiyah', 'name_ar' => 'حي القادسية', 'price' => 5],
            ['id' => 73, 'zone_id' => 1, 'name' => 'Al Safa', 'name_ar' => 'حي الصفا', 'price' => 5],
            ['id' => 74, 'zone_id' => 1, 'name' => 'Al Olaya', 'name_ar' => 'حي العليا', 'price' => 5],
            ['id' => 75, 'zone_id' => 1, 'name' => 'Al Duraihemiyah', 'name_ar' => 'حي الدريهمية', 'price' => 5],
            ['id' => 76, 'zone_id' => 1, 'name' => 'Al Iskan', 'name_ar' => 'حي الاسكان', 'price' => 5],
            ['id' => 77, 'zone_id' => 1, 'name' => 'Al Salam', 'name_ar' => 'حي السلام', 'price' => 5],
            ['id' => 78, 'zone_id' => 1, 'name' => 'Al Manar', 'name_ar' => 'حي المنار', 'price' => 5],
            ['id' => 79, 'zone_id' => 1, 'name' => 'East Naseem', 'name_ar' => 'حي النسيم الشرقي', 'price' => 5],
            ['id' => 80, 'zone_id' => 1, 'name' => 'Al Quds', 'name_ar' => 'حي القدس', 'price' => 5],
            ['id' => 81, 'zone_id' => 1, 'name' => 'Al Wadi', 'name_ar' => 'حي الوادي', 'price' => 5],
            ['id' => 82, 'zone_id' => 1, 'name' => 'Al Nafel', 'name_ar' => 'حي النفل', 'price' => 5],
            ['id' => 83, 'zone_id' => 1, 'name' => 'Al Maseef', 'name_ar' => 'حي المصيف', 'price' => 5],
            ['id' => 84, 'zone_id' => 1, 'name' => 'Al Taawun', 'name_ar' => 'حي التعاون', 'price' => 5],
            ['id' => 85, 'zone_id' => 1, 'name' => 'Al Ezdihar', 'name_ar' => 'حي الازدهار', 'price' => 5],
            ['id' => 86, 'zone_id' => 1, 'name' => 'Al Andalus', 'name_ar' => 'حي الاندلس', 'price' => 5],
            ['id' => 87, 'zone_id' => 1, 'name' => 'Al Rawdah', 'name_ar' => 'حي الروضة', 'price' => 5],
            ['id' => 88, 'zone_id' => 1, 'name' => 'Al Rawabi', 'name_ar' => 'حي الروابي', 'price' => 5],
            ['id' => 89, 'zone_id' => 1, 'name' => 'Al Rayan', 'name_ar' => 'حي الريان', 'price' => 5],
            ['id' => 90, 'zone_id' => 1, 'name' => 'Dhahrat Al Badeah', 'name_ar' => 'حي ظهرة البديعة', 'price' => 5],
            ['id' => 91, 'zone_id' => 1, 'name' => 'Al Nadheem', 'name_ar' => 'حي النظيم', 'price' => 5],
            ['id' => 92, 'zone_id' => 1, 'name' => 'Al Rimayah', 'name_ar' => 'حي الرماية', 'price' => 5],
            ['id' => 93, 'zone_id' => 1, 'name' => 'Al Bariyah', 'name_ar' => 'حي البرية', 'price' => 5],
            ['id' => 94, 'zone_id' => 1, 'name' => 'Taybah', 'name_ar' => 'حي طيبة', 'price' => 5],
            ['id' => 95, 'zone_id' => 1, 'name' => 'Mansuriyah', 'name_ar' => 'حي المنصورية', 'price' => 5],
            ['id' => 96, 'zone_id' => 1, 'name' => 'Dahiyat Namar', 'name_ar' => 'حي ضاحية نمار', 'price' => 5],
            ['id' => 97, 'zone_id' => 1, 'name' => 'Al Misfat', 'name_ar' => 'حي المصفاة', 'price' => 5],
            ['id' => 98, 'zone_id' => 1, 'name' => 'Assafarat', 'name_ar' => 'حي السفارات', 'price' => 5],
            ['id' => 99, 'zone_id' => 1, 'name' => 'Khashm Al An', 'name_ar' => 'خشم العان', 'price' => 5],
            ['id' => 100, 'zone_id' => 1, 'name' => 'Qurtubah', 'name_ar' => 'حي قرطبة', 'price' => 5],
            ['id' => 101, 'zone_id' => 1, 'name' => 'Tuwaiq', 'name_ar' => 'حي طويق', 'price' => 5],
            ['id' => 102, 'zone_id' => 1, 'name' => 'Al Awaly', 'name_ar' => 'حي العوالي', 'price' => 5],
            ['id' => 103, 'zone_id' => 1, 'name' => 'Ar Rabie', 'name_ar' => 'حي الربيع', 'price' => 5],
            ['id' => 104, 'zone_id' => 1, 'name' => 'Al Mughrazat', 'name_ar' => 'حي المغرزات', 'price' => 5],
            ['id' => 105, 'zone_id' => 1, 'name' => 'Al Sulay', 'name_ar' => 'حي السلي', 'price' => 5],
            ['id' => 106, 'zone_id' => 1, 'name' => 'Al Aqeeq', 'name_ar' => 'حي العقيق', 'price' => 5],
            ['id' => 107, 'zone_id' => 1, 'name' => 'Al Nakheel', 'name_ar' => 'حي النخيل', 'price' => 5],
            ['id' => 108, 'zone_id' => 2, 'name' => 'Ajyad', 'name_ar' => 'أجياد', 'price' => 5],
            ['id' => 109, 'zone_id' => 2, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 110, 'zone_id' => 2, 'name' => 'Al Misfalah', 'name_ar' => 'المسفلة', 'price' => 5],
            ['id' => 111, 'zone_id' => 2, 'name' => 'Al Haram', 'name_ar' => 'الحرم', 'price' => 5],
            ['id' => 112, 'zone_id' => 2, 'name' => 'Al Awali', 'name_ar' => 'العوالي', 'price' => 5],
            ['id' => 113, 'zone_id' => 2, 'name' => 'Al Shawqiyah', 'name_ar' => 'الشوقية', 'price' => 5],
            ['id' => 114, 'zone_id' => 2, 'name' => 'Al Kakiyah', 'name_ar' => 'الكعكية', 'price' => 5],
            ['id' => 115, 'zone_id' => 2, 'name' => 'Al Hindawiyah', 'name_ar' => 'الهنداوية', 'price' => 5],
            ['id' => 116, 'zone_id' => 2, 'name' => 'Al Taysir', 'name_ar' => 'التيسير', 'price' => 5],
            ['id' => 117, 'zone_id' => 2, 'name' => 'Al Mansur', 'name_ar' => 'المنصور', 'price' => 5],
            ['id' => 118, 'zone_id' => 2, 'name' => 'Al Rusayfah', 'name_ar' => 'الرصيفة', 'price' => 5],
            ['id' => 119, 'zone_id' => 2, 'name' => 'Al Jamrah', 'name_ar' => 'الجمرات', 'price' => 5],
            ['id' => 120, 'zone_id' => 2, 'name' => 'Al Maabdah', 'name_ar' => 'المعابدة', 'price' => 5],
            ['id' => 121, 'zone_id' => 2, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 122, 'zone_id' => 2, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 123, 'zone_id' => 2, 'name' => 'Al Zahra', 'name_ar' => 'الزهراء', 'price' => 5],
            ['id' => 124, 'zone_id' => 2, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 125, 'zone_id' => 2, 'name' => 'Al Rashidiyah', 'name_ar' => 'الرشيدية', 'price' => 5],
            ['id' => 126, 'zone_id' => 2, 'name' => 'Al Batha', 'name_ar' => 'البطحاء', 'price' => 5],
            ['id' => 127, 'zone_id' => 2, 'name' => 'Al Hamra', 'name_ar' => 'الحمراء', 'price' => 5],
            ['id' => 128, 'zone_id' => 3, 'name' => 'Al Anbariyah', 'name_ar' => 'العنبرية', 'price' => 5],
            ['id' => 129, 'zone_id' => 3, 'name' => 'Al Awali', 'name_ar' => 'العوالي', 'price' => 5],
            ['id' => 130, 'zone_id' => 3, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 131, 'zone_id' => 3, 'name' => 'Al Iskan', 'name_ar' => 'الإسكان', 'price' => 5],
            ['id' => 132, 'zone_id' => 3, 'name' => 'Qurban', 'name_ar' => 'قربان', 'price' => 5],
            ['id' => 133, 'zone_id' => 3, 'name' => 'Al Jamawat', 'name_ar' => 'الجماوات', 'price' => 5],
            ['id' => 134, 'zone_id' => 3, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 135, 'zone_id' => 3, 'name' => 'Al Aridh', 'name_ar' => 'العريض', 'price' => 5],
            ['id' => 136, 'zone_id' => 3, 'name' => 'Al Jumuah', 'name_ar' => 'الجمعة', 'price' => 5],
            ['id' => 137, 'zone_id' => 3, 'name' => 'Al Sih', 'name_ar' => 'السيح', 'price' => 5],
            ['id' => 138, 'zone_id' => 3, 'name' => 'Bani Muawiyah', 'name_ar' => 'بني معاوية', 'price' => 5],
            ['id' => 139, 'zone_id' => 3, 'name' => 'Al Rayah', 'name_ar' => 'الراية', 'price' => 5],
            ['id' => 140, 'zone_id' => 3, 'name' => 'Al Usbah', 'name_ar' => 'العصبة', 'price' => 5],
            ['id' => 141, 'zone_id' => 3, 'name' => 'Al Mahdiyah', 'name_ar' => 'المهدية', 'price' => 5],
            ['id' => 142, 'zone_id' => 3, 'name' => 'Al Mabuth', 'name_ar' => 'المبعوث', 'price' => 5],
            ['id' => 143, 'zone_id' => 3, 'name' => 'Al Shuraybat', 'name_ar' => 'شوران', 'price' => 5],
            ['id' => 144, 'zone_id' => 3, 'name' => 'Al Difa', 'name_ar' => 'الدفاع', 'price' => 5],
            ['id' => 145, 'zone_id' => 3, 'name' => 'Al Iskan', 'name_ar' => 'الإسكان', 'price' => 5],
            ['id' => 146, 'zone_id' => 4, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 147, 'zone_id' => 4, 'name' => 'Al Mazruiyah', 'name_ar' => 'المزروعية', 'price' => 5],
            ['id' => 148, 'zone_id' => 4, 'name' => 'Al Adamah', 'name_ar' => 'العدامة', 'price' => 5],
            ['id' => 149, 'zone_id' => 4, 'name' => 'Al Badi', 'name_ar' => 'البديع', 'price' => 5],
            ['id' => 150, 'zone_id' => 4, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 151, 'zone_id' => 4, 'name' => 'Al Qashlah', 'name_ar' => 'القشلة', 'price' => 5],
            ['id' => 152, 'zone_id' => 4, 'name' => 'Al Dawasir', 'name_ar' => 'الدواسر', 'price' => 5],
            ['id' => 153, 'zone_id' => 4, 'name' => 'Al Jalawiyah', 'name_ar' => 'الجلوية', 'price' => 5],
            ['id' => 154, 'zone_id' => 5, 'name' => 'Al Manhal', 'name_ar' => 'المنهل', 'price' => 5],
            ['id' => 155, 'zone_id' => 5, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 156, 'zone_id' => 5, 'name' => 'Al Muftaha', 'name_ar' => 'المفتاحة', 'price' => 5],
            ['id' => 157, 'zone_id' => 5, 'name' => 'Al Wardatayn', 'name_ar' => 'الوردتين', 'price' => 5],
            ['id' => 158, 'zone_id' => 5, 'name' => 'Al Shifa', 'name_ar' => 'الشفا', 'price' => 5],
            ['id' => 159, 'zone_id' => 5, 'name' => 'Al Mashhad', 'name_ar' => 'المشهد', 'price' => 5],
            ['id' => 160, 'zone_id' => 5, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 161, 'zone_id' => 6, 'name' => 'Al Murooj', 'name_ar' => 'المروج', 'price' => 5],
            ['id' => 162, 'zone_id' => 6, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 163, 'zone_id' => 6, 'name' => 'Al Sultanah', 'name_ar' => 'السلطانة', 'price' => 5],
            ['id' => 164, 'zone_id' => 6, 'name' => 'Al Muruj', 'name_ar' => 'المروج', 'price' => 5],
            ['id' => 165, 'zone_id' => 6, 'name' => 'Al Wurud', 'name_ar' => 'الورود', 'price' => 5],
            ['id' => 166, 'zone_id' => 6, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 167, 'zone_id' => 6, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 168, 'zone_id' => 6, 'name' => 'Al Qadisiyah', 'name_ar' => 'القادسية', 'price' => 5],
            ['id' => 169, 'zone_id' => 6, 'name' => 'Al Naseem', 'name_ar' => 'النسيم', 'price' => 5],
            ['id' => 170, 'zone_id' => 6, 'name' => 'Al Rajhi', 'name_ar' => 'الراجحي', 'price' => 5],
            ['id' => 171, 'zone_id' => 7, 'name' => 'Al Naqrah', 'name_ar' => 'النقرة', 'price' => 5],
            ['id' => 172, 'zone_id' => 7, 'name' => 'Al Wusayta', 'name_ar' => 'الوسيطاء', 'price' => 5],
            ['id' => 173, 'zone_id' => 7, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 174, 'zone_id' => 7, 'name' => 'Al Khuzama', 'name_ar' => 'الخزامى', 'price' => 5],
            ['id' => 175, 'zone_id' => 7, 'name' => 'Al Muntazah', 'name_ar' => 'المنتزه', 'price' => 5],
            ['id' => 176, 'zone_id' => 7, 'name' => 'Al Sahafah', 'name_ar' => 'الصحافة', 'price' => 5],
            ['id' => 177, 'zone_id' => 7, 'name' => 'Al Mahatta', 'name_ar' => 'المحطة', 'price' => 5],
            ['id' => 178, 'zone_id' => 7, 'name' => 'Al Jamiyin', 'name_ar' => 'الجامعيين', 'price' => 5],
            ['id' => 179, 'zone_id' => 8, 'name' => 'Al Mashael', 'name_ar' => 'المشاعل', 'price' => 5],
            ['id' => 180, 'zone_id' => 8, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 181, 'zone_id' => 8, 'name' => 'Al Muruj', 'name_ar' => 'المروج', 'price' => 5],
            ['id' => 182, 'zone_id' => 8, 'name' => 'Al Rabwah', 'name_ar' => 'الربوة', 'price' => 5],
            ['id' => 183, 'zone_id' => 8, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 184, 'zone_id' => 9, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 185, 'zone_id' => 9, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 186, 'zone_id' => 9, 'name' => 'Al Safa', 'name_ar' => 'الصفا', 'price' => 5],
            ['id' => 187, 'zone_id' => 9, 'name' => 'Al Suways', 'name_ar' => 'السويس', 'price' => 5],
            ['id' => 188, 'zone_id' => 9, 'name' => 'Al Souq', 'name_ar' => 'السوق', 'price' => 5],
            ['id' => 189, 'zone_id' => 9, 'name' => 'Al Shamia', 'name_ar' => 'الشامية', 'price' => 5],
            ['id' => 190, 'zone_id' => 9, 'name' => 'Al Manhal', 'name_ar' => 'المنهل', 'price' => 5],
            ['id' => 191, 'zone_id' => 9, 'name' => 'Al Nakheel', 'name_ar' => 'النخيل', 'price' => 5],
            ['id' => 192, 'zone_id' => 10, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 193, 'zone_id' => 10, 'name' => 'Al Makhayim', 'name_ar' => 'المخيم', 'price' => 5],
            ['id' => 194, 'zone_id' => 10, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 195, 'zone_id' => 10, 'name' => 'Al Faysaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 196, 'zone_id' => 10, 'name' => 'Al Shorfa', 'name_ar' => 'الشرفة', 'price' => 5],
            ['id' => 197, 'zone_id' => 10, 'name' => 'Al Aba', 'name_ar' => 'العبا', 'price' => 5],
            ['id' => 198, 'zone_id' => 10, 'name' => 'Al Gharbi', 'name_ar' => 'الغربي', 'price' => 5],
            ['id' => 199, 'zone_id' => 11, 'name' => 'Al Baha', 'name_ar' => 'الباحة', 'price' => 5],
            ['id' => 200, 'zone_id' => 11, 'name' => 'Al Hosn', 'name_ar' => 'الحصن', 'price' => 5],
            ['id' => 201, 'zone_id' => 11, 'name' => 'Al Zahra', 'name_ar' => 'الزهراء', 'price' => 5],
            ['id' => 202, 'zone_id' => 11, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 203, 'zone_id' => 11, 'name' => 'Al Shafa', 'name_ar' => 'الشفا', 'price' => 5],
            ['id' => 204, 'zone_id' => 12, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 205, 'zone_id' => 12, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 206, 'zone_id' => 12, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 207, 'zone_id' => 12, 'name' => 'Al Suwaidi', 'name_ar' => 'السويدي', 'price' => 5],
            ['id' => 208, 'zone_id' => 12, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 209, 'zone_id' => 13, 'name' => 'Al Safra', 'name_ar' => 'الصفراء', 'price' => 5],
            ['id' => 210, 'zone_id' => 13, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 211, 'zone_id' => 13, 'name' => 'Al Iskan', 'name_ar' => 'الإسكان', 'price' => 5],
            ['id' => 212, 'zone_id' => 13, 'name' => 'Al Muntazah', 'name_ar' => 'المنتزه', 'price' => 5],
            ['id' => 213, 'zone_id' => 13, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 214, 'zone_id' => 14, 'name' => 'Al Andalus', 'name_ar' => 'الأندلس', 'price' => 5],
            ['id' => 215, 'zone_id' => 14, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 216, 'zone_id' => 14, 'name' => 'Al Khuzama', 'name_ar' => 'الخزامى', 'price' => 5],
            ['id' => 217, 'zone_id' => 14, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 218, 'zone_id' => 14, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 219, 'zone_id' => 14, 'name' => 'Al Salam', 'name_ar' => 'السلام', 'price' => 5],
            ['id' => 220, 'zone_id' => 14, 'name' => 'Al Mashrif', 'name_ar' => 'المشرف', 'price' => 5],
            ['id' => 221, 'zone_id' => 14, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 222, 'zone_id' => 15, 'name' => 'Al-Ghat', 'name_ar' => 'الغاط', 'price' => 5],
            ['id' => 223, 'zone_id' => 15, 'name' => 'Al-Majmaah', 'name_ar' => 'المجمعة', 'price' => 5],
            ['id' => 224, 'zone_id' => 15, 'name' => 'Jalajil', 'name_ar' => 'جلاجل', 'price' => 5],
            ['id' => 225, 'zone_id' => 15, 'name' => 'Rawdat Sudair', 'name_ar' => 'روضة سدير', 'price' => 5],
            ['id' => 226, 'zone_id' => 15, 'name' => 'Tumair', 'name_ar' => 'تمير', 'price' => 5],
            ['id' => 227, 'zone_id' => 15, 'name' => 'Ushayqir', 'name_ar' => 'أشيقر', 'price' => 5],
            ['id' => 228, 'zone_id' => 16, 'name' => 'Al Dawadmi', 'name_ar' => 'الدوادمي', 'price' => 5],
            ['id' => 229, 'zone_id' => 16, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 230, 'zone_id' => 16, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 231, 'zone_id' => 16, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 232, 'zone_id' => 16, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 233, 'zone_id' => 17, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 234, 'zone_id' => 17, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 235, 'zone_id' => 17, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 236, 'zone_id' => 17, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 237, 'zone_id' => 17, 'name' => 'Al Shifa', 'name_ar' => 'الشفا', 'price' => 5],
            ['id' => 238, 'zone_id' => 18, 'name' => 'Al Hamra', 'name_ar' => 'الحمراء', 'price' => 5],
            ['id' => 239, 'zone_id' => 18, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 240, 'zone_id' => 18, 'name' => 'Al Zahra', 'name_ar' => 'الزهراء', 'price' => 5],
            ['id' => 241, 'zone_id' => 18, 'name' => 'Al Salamah', 'name_ar' => 'السلامة', 'price' => 5],
            ['id' => 242, 'zone_id' => 18, 'name' => 'Al Safa', 'name_ar' => 'الصفا', 'price' => 5],
            ['id' => 243, 'zone_id' => 18, 'name' => 'Al Marwah', 'name_ar' => 'المروة', 'price' => 5],
            ['id' => 244, 'zone_id' => 18, 'name' => 'Al Bawadi', 'name_ar' => 'البوادي', 'price' => 5],
            ['id' => 245, 'zone_id' => 18, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 246, 'zone_id' => 18, 'name' => 'Al Rabwah', 'name_ar' => 'الربوة', 'price' => 5],
            ['id' => 247, 'zone_id' => 18, 'name' => 'Al Naeem', 'name_ar' => 'النعيم', 'price' => 5],
            ['id' => 248, 'zone_id' => 18, 'name' => 'Al Basateen', 'name_ar' => 'البساتين', 'price' => 5],
            ['id' => 249, 'zone_id' => 18, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 250, 'zone_id' => 18, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 251, 'zone_id' => 18, 'name' => 'Al Muhammadiyah', 'name_ar' => 'المحمدية', 'price' => 5],
            ['id' => 252, 'zone_id' => 18, 'name' => 'Al Nahdah', 'name_ar' => 'النهضة', 'price' => 5],
            ['id' => 253, 'zone_id' => 18, 'name' => 'Al Andalus', 'name_ar' => 'الأندلس', 'price' => 5],
            ['id' => 254, 'zone_id' => 18, 'name' => 'Al Baghdadiyah', 'name_ar' => 'البغدادية', 'price' => 5],
            ['id' => 255, 'zone_id' => 18, 'name' => 'Al Balad', 'name_ar' => 'البلد', 'price' => 5],
            ['id' => 256, 'zone_id' => 18, 'name' => 'Al Hindawiyah', 'name_ar' => 'الهنداوية', 'price' => 5],
            ['id' => 257, 'zone_id' => 18, 'name' => 'Al Samer', 'name_ar' => 'السامر', 'price' => 5],
            ['id' => 258, 'zone_id' => 18, 'name' => 'Al Ajwad', 'name_ar' => 'الأجواد', 'price' => 5],
            ['id' => 259, 'zone_id' => 18, 'name' => 'Al Manar', 'name_ar' => 'المنار', 'price' => 5],
            ['id' => 260, 'zone_id' => 18, 'name' => 'Al Muntazahat', 'name_ar' => 'المنتزهات', 'price' => 5],
            ['id' => 261, 'zone_id' => 18, 'name' => 'Al Montazah', 'name_ar' => 'المنتزه', 'price' => 5],
            ['id' => 262, 'zone_id' => 18, 'name' => 'Obhur Al Shamaliyah', 'name_ar' => 'أبحر الشمالية', 'price' => 5],
            ['id' => 263, 'zone_id' => 18, 'name' => 'Obhur Al Janubiyah', 'name_ar' => 'أبحر الجنوبية', 'price' => 5],
            ['id' => 264, 'zone_id' => 18, 'name' => 'Al Lulu', 'name_ar' => 'اللؤلؤ', 'price' => 5],
            ['id' => 265, 'zone_id' => 18, 'name' => 'Al Waha', 'name_ar' => 'الواحة', 'price' => 5],
            ['id' => 266, 'zone_id' => 18, 'name' => 'Al Rehab', 'name_ar' => 'الرحاب', 'price' => 5],
            ['id' => 267, 'zone_id' => 18, 'name' => 'Al Mishrifiyah', 'name_ar' => 'المشرفة', 'price' => 5],
            ['id' => 268, 'zone_id' => 18, 'name' => 'Al Qurayyat', 'name_ar' => 'القريات', 'price' => 5],
            ['id' => 269, 'zone_id' => 18, 'name' => 'Al Ruwais', 'name_ar' => 'الرويس', 'price' => 5],
            ['id' => 270, 'zone_id' => 19, 'name' => 'Al Shafa', 'name_ar' => 'الشفا', 'price' => 5],
            ['id' => 271, 'zone_id' => 19, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 272, 'zone_id' => 19, 'name' => 'Al Qutbiyyah', 'name_ar' => 'القطبية', 'price' => 5],
            ['id' => 273, 'zone_id' => 19, 'name' => 'Al Salamah', 'name_ar' => 'السلامة', 'price' => 5],
            ['id' => 274, 'zone_id' => 19, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 275, 'zone_id' => 19, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 276, 'zone_id' => 19, 'name' => 'Al Wasam', 'name_ar' => 'الوسام', 'price' => 5],
            ['id' => 277, 'zone_id' => 19, 'name' => 'Al Jal', 'name_ar' => 'الجال', 'price' => 5],
            ['id' => 278, 'zone_id' => 19, 'name' => 'Al Muthanna', 'name_ar' => 'المثناة', 'price' => 5],
            ['id' => 279, 'zone_id' => 19, 'name' => 'Al Qamariyah', 'name_ar' => 'القمرية', 'price' => 5],
            ['id' => 280, 'zone_id' => 20, 'name' => 'Rabigh', 'name_ar' => 'رابغ', 'price' => 5],
            ['id' => 281, 'zone_id' => 20, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 282, 'zone_id' => 20, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 283, 'zone_id' => 20, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 284, 'zone_id' => 20, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 285, 'zone_id' => 21, 'name' => 'Al Qunfudhah', 'name_ar' => 'القنفذة', 'price' => 5],
            ['id' => 286, 'zone_id' => 21, 'name' => 'Al Nakhil', 'name_ar' => 'النخيل', 'price' => 5],
            ['id' => 287, 'zone_id' => 21, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 288, 'zone_id' => 21, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 289, 'zone_id' => 21, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 290, 'zone_id' => 22, 'name' => 'Al Nakheel', 'name_ar' => 'النخيل', 'price' => 5],
            ['id' => 291, 'zone_id' => 22, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 292, 'zone_id' => 22, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 293, 'zone_id' => 22, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 294, 'zone_id' => 22, 'name' => 'Al Buhayrat', 'name_ar' => 'البحيرات', 'price' => 5],
            ['id' => 295, 'zone_id' => 22, 'name' => 'Al Majid', 'name_ar' => 'المجد', 'price' => 5],
            ['id' => 296, 'zone_id' => 22, 'name' => 'Al Samir', 'name_ar' => 'السميري', 'price' => 5],
            ['id' => 297, 'zone_id' => 22, 'name' => 'Al Zuhur', 'name_ar' => 'الزهور', 'price' => 5],
            ['id' => 298, 'zone_id' => 23, 'name' => 'Badr', 'name_ar' => 'بدر', 'price' => 5],
            ['id' => 299, 'zone_id' => 23, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 300, 'zone_id' => 23, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 301, 'zone_id' => 23, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 302, 'zone_id' => 24, 'name' => 'Al Ula', 'name_ar' => 'العلا', 'price' => 5],
            ['id' => 303, 'zone_id' => 24, 'name' => 'Al Jadidah', 'name_ar' => 'الجديدة', 'price' => 5],
            ['id' => 304, 'zone_id' => 24, 'name' => 'Al Sukhairat', 'name_ar' => 'الصخيرات', 'price' => 5],
            ['id' => 305, 'zone_id' => 24, 'name' => 'Al Madinah', 'name_ar' => 'المدينة', 'price' => 5],
            ['id' => 306, 'zone_id' => 24, 'name' => 'Al Wadi', 'name_ar' => 'الوادي', 'price' => 5],
            ['id' => 307, 'zone_id' => 25, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 308, 'zone_id' => 25, 'name' => 'Al Mazruiyah', 'name_ar' => 'المزروعية', 'price' => 5],
            ['id' => 309, 'zone_id' => 25, 'name' => 'Al Adamah', 'name_ar' => 'العدامة', 'price' => 5],
            ['id' => 310, 'zone_id' => 25, 'name' => 'Al Shati Al Gharbi', 'name_ar' => 'الشاطئ الغربي', 'price' => 5],
            ['id' => 311, 'zone_id' => 25, 'name' => 'Al Shati Al Sharqi', 'name_ar' => 'الشاطئ الشرقي', 'price' => 5],
            ['id' => 312, 'zone_id' => 25, 'name' => 'Al Badi', 'name_ar' => 'البديع', 'price' => 5],
            ['id' => 313, 'zone_id' => 25, 'name' => 'Al Qashlah', 'name_ar' => 'القشلة', 'price' => 5],
            ['id' => 314, 'zone_id' => 25, 'name' => 'Al Jalawiyah', 'name_ar' => 'الجلوية', 'price' => 5],
            ['id' => 315, 'zone_id' => 25, 'name' => 'Al Nakhil', 'name_ar' => 'النخيل', 'price' => 5],
            ['id' => 316, 'zone_id' => 25, 'name' => 'Al Zuhur', 'name_ar' => 'الزهور', 'price' => 5],
            ['id' => 317, 'zone_id' => 25, 'name' => 'Al Manar', 'name_ar' => 'المنار', 'price' => 5],
            ['id' => 318, 'zone_id' => 25, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 319, 'zone_id' => 25, 'name' => 'Al Nahdah', 'name_ar' => 'النهضة', 'price' => 5],
            ['id' => 320, 'zone_id' => 25, 'name' => 'Al Safa', 'name_ar' => 'الصفا', 'price' => 5],
            ['id' => 321, 'zone_id' => 25, 'name' => 'Al Rabi', 'name_ar' => 'الربيع', 'price' => 5],
            ['id' => 322, 'zone_id' => 25, 'name' => 'Al Badiyah', 'name_ar' => 'البادية', 'price' => 5],
            ['id' => 323, 'zone_id' => 25, 'name' => 'Al Noor', 'name_ar' => 'النور', 'price' => 5],
            ['id' => 324, 'zone_id' => 25, 'name' => 'Al Anud', 'name_ar' => 'العنود', 'price' => 5],
            ['id' => 325, 'zone_id' => 25, 'name' => 'Al Khodariyah', 'name_ar' => 'الخضرية', 'price' => 5],
            ['id' => 326, 'zone_id' => 25, 'name' => 'Al Sharq', 'name_ar' => 'الشرق', 'price' => 5],
            ['id' => 327, 'zone_id' => 25, 'name' => 'Ibn Khaldun', 'name_ar' => 'ابن خلدون', 'price' => 5],
            ['id' => 328, 'zone_id' => 25, 'name' => 'Al Sinaiyah', 'name_ar' => 'الصناعية', 'price' => 5],
            ['id' => 329, 'zone_id' => 25, 'name' => 'Al Basatin', 'name_ar' => 'البساتين', 'price' => 5],
            ['id' => 330, 'zone_id' => 25, 'name' => 'Al Fayha', 'name_ar' => 'الفيحاء', 'price' => 5],
            ['id' => 331, 'zone_id' => 25, 'name' => 'Taybah', 'name_ar' => 'طيبة', 'price' => 5],
            ['id' => 332, 'zone_id' => 25, 'name' => 'Al Jawhara', 'name_ar' => 'الجوهرة', 'price' => 5],
            ['id' => 333, 'zone_id' => 25, 'name' => 'Al Naseem', 'name_ar' => 'النسيم', 'price' => 5],
            ['id' => 334, 'zone_id' => 25, 'name' => 'Al Shifa', 'name_ar' => 'الشفاء', 'price' => 5],
            ['id' => 335, 'zone_id' => 25, 'name' => 'Al Jamiyin', 'name_ar' => 'الجامعيين', 'price' => 5],
            ['id' => 336, 'zone_id' => 25, 'name' => 'Al Rabiyah', 'name_ar' => 'الرابية', 'price' => 5],
            ['id' => 337, 'zone_id' => 25, 'name' => 'Al Khalidiyah Al Janubiyah', 'name_ar' => 'الخالدية الجنوبية', 'price' => 5],
            ['id' => 338, 'zone_id' => 25, 'name' => 'Al Nakheel', 'name_ar' => 'النخيل', 'price' => 5],
            ['id' => 339, 'zone_id' => 25, 'name' => 'Al Ferdous', 'name_ar' => 'الفردوس', 'price' => 5],
            ['id' => 340, 'zone_id' => 25, 'name' => 'Al Muraikabat', 'name_ar' => 'المريكبات', 'price' => 5],
            ['id' => 341, 'zone_id' => 25, 'name' => 'Al Danah', 'name_ar' => 'الدانة', 'price' => 5],
            ['id' => 342, 'zone_id' => 25, 'name' => 'Al Shuala', 'name_ar' => 'الشعلة', 'price' => 5],
            ['id' => 343, 'zone_id' => 25, 'name' => 'Al Qazzaz', 'name_ar' => 'القزاز', 'price' => 5],
            ['id' => 344, 'zone_id' => 25, 'name' => 'Qasr Al Khaleej', 'name_ar' => 'قصر الخليج', 'price' => 5],
            ['id' => 345, 'zone_id' => 25, 'name' => 'Al Nawrass', 'name_ar' => 'النورس', 'price' => 5],
            ['id' => 346, 'zone_id' => 26, 'name' => 'Al Hamra', 'name_ar' => 'الحمراء', 'price' => 5],
            ['id' => 347, 'zone_id' => 26, 'name' => 'Al Aqrabiyah', 'name_ar' => 'العقربية', 'price' => 5],
            ['id' => 348, 'zone_id' => 26, 'name' => 'Al Thuqbah', 'name_ar' => 'الثقبة', 'price' => 5],
            ['id' => 349, 'zone_id' => 26, 'name' => 'Al Khobar Al Shamaliyah', 'name_ar' => 'الخبر الشمالية', 'price' => 5],
            ['id' => 350, 'zone_id' => 26, 'name' => 'Al Khobar Al Janubiyah', 'name_ar' => 'الخبر الجنوبية', 'price' => 5],
            ['id' => 351, 'zone_id' => 26, 'name' => 'Al Corniche', 'name_ar' => 'الكورنيش', 'price' => 5],
            ['id' => 352, 'zone_id' => 26, 'name' => 'Al Rawabi', 'name_ar' => 'الروابي', 'price' => 5],
            ['id' => 353, 'zone_id' => 26, 'name' => 'Al Andalus', 'name_ar' => 'الأندلس', 'price' => 5],
            ['id' => 354, 'zone_id' => 26, 'name' => 'Al Bustan', 'name_ar' => 'البستان', 'price' => 5],
            ['id' => 355, 'zone_id' => 26, 'name' => 'Al Sahel', 'name_ar' => 'الساحل', 'price' => 5],
            ['id' => 356, 'zone_id' => 26, 'name' => 'Al Lulu', 'name_ar' => 'اللؤلؤ', 'price' => 5],
            ['id' => 357, 'zone_id' => 26, 'name' => 'Al Mursalat', 'name_ar' => 'المرسلات', 'price' => 5],
            ['id' => 358, 'zone_id' => 26, 'name' => 'Al Hizam Al Dhahabi', 'name_ar' => 'الحزام الذهبي', 'price' => 5],
            ['id' => 359, 'zone_id' => 26, 'name' => 'Al Amwaj', 'name_ar' => 'الأمواج', 'price' => 5],
            ['id' => 360, 'zone_id' => 26, 'name' => 'Al Mahaa', 'name_ar' => 'المها', 'price' => 5],
            ['id' => 361, 'zone_id' => 26, 'name' => 'Al Bandariyah', 'name_ar' => 'البندرية', 'price' => 5],
            ['id' => 362, 'zone_id' => 26, 'name' => 'Al Ulya', 'name_ar' => 'العليا', 'price' => 5],
            ['id' => 363, 'zone_id' => 26, 'name' => 'Al Khour', 'name_ar' => 'الخور', 'price' => 5],
            ['id' => 364, 'zone_id' => 26, 'name' => 'Al Marina', 'name_ar' => 'المارينا', 'price' => 5],
            ['id' => 365, 'zone_id' => 26, 'name' => 'Al Rakah Al Janubiyah', 'name_ar' => 'الراكة الجنوبية', 'price' => 5],
            ['id' => 366, 'zone_id' => 26, 'name' => 'Al Rakah Al Shamaliyah', 'name_ar' => 'الراكة الشمالية', 'price' => 5],
            ['id' => 367, 'zone_id' => 26, 'name' => 'Al Taawun', 'name_ar' => 'التعاون', 'price' => 5],
            ['id' => 368, 'zone_id' => 26, 'name' => 'Al Sawari', 'name_ar' => 'الصواري', 'price' => 5],
            ['id' => 369, 'zone_id' => 26, 'name' => 'Al Ihsan', 'name_ar' => 'الإحسان', 'price' => 5],
            ['id' => 370, 'zone_id' => 27, 'name' => 'Al Huwaylat', 'name_ar' => 'الحويلات', 'price' => 5],
            ['id' => 371, 'zone_id' => 27, 'name' => 'Al Najd', 'name_ar' => 'نجد', 'price' => 5],
            ['id' => 372, 'zone_id' => 27, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 373, 'zone_id' => 27, 'name' => 'Al Jawharah', 'name_ar' => 'الجوهرة', 'price' => 5],
            ['id' => 374, 'zone_id' => 27, 'name' => 'Al Lulu', 'name_ar' => 'اللؤلؤ', 'price' => 5],
            ['id' => 375, 'zone_id' => 27, 'name' => 'Darine', 'name_ar' => 'دارين', 'price' => 5],
            ['id' => 376, 'zone_id' => 27, 'name' => 'Al Dabab', 'name_ar' => 'الضباب', 'price' => 5],
            ['id' => 377, 'zone_id' => 27, 'name' => 'Gharnatah', 'name_ar' => 'غرناطة', 'price' => 5],
            ['id' => 378, 'zone_id' => 27, 'name' => '1st Industrial Area', 'name_ar' => 'المنطقة الصناعية الاولى', 'price' => 5],
            ['id' => 379, 'zone_id' => 27, 'name' => 'Al Sudair', 'name_ar' => 'سدير', 'price' => 5],
            ['id' => 380, 'zone_id' => 27, 'name' => 'Al Waha', 'name_ar' => 'الواحة', 'price' => 5],
            ['id' => 381, 'zone_id' => 27, 'name' => 'Al Salam', 'name_ar' => 'السلام', 'price' => 5],
            ['id' => 382, 'zone_id' => 27, 'name' => 'Industrial Area', 'name_ar' => 'المنطقة الصناعية', 'price' => 5],
            ['id' => 383, 'zone_id' => 27, 'name' => 'Al Makkah', 'name_ar' => 'مكة', 'price' => 5],
            ['id' => 384, 'zone_id' => 27, 'name' => 'Al Andalus', 'name_ar' => 'الأندلس', 'price' => 5],
            ['id' => 385, 'zone_id' => 27, 'name' => 'Al Hamra', 'name_ar' => 'الحمراء', 'price' => 5],
            ['id' => 386, 'zone_id' => 27, 'name' => '3rd Industrial Area', 'name_ar' => 'المنطقة الصناعية الثالثة', 'price' => 5],
            ['id' => 387, 'zone_id' => 27, 'name' => 'Al Yarmouk', 'name_ar' => 'اليرموك', 'price' => 5],
            ['id' => 388, 'zone_id' => 27, 'name' => 'Al Farouq', 'name_ar' => 'الفاروق', 'price' => 5],
            ['id' => 389, 'zone_id' => 27, 'name' => 'Al Khuzama', 'name_ar' => 'الخزامى', 'price' => 5],
            ['id' => 390, 'zone_id' => 27, 'name' => 'Al Basatin', 'name_ar' => 'البستان', 'price' => 5],
            ['id' => 391, 'zone_id' => 27, 'name' => 'Al Quds', 'name_ar' => 'القدس', 'price' => 5],
            ['id' => 392, 'zone_id' => 27, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 393, 'zone_id' => 27, 'name' => 'Al Fayha', 'name_ar' => 'الفيحاء', 'price' => 5],
            ['id' => 394, 'zone_id' => 27, 'name' => 'Al Taawun', 'name_ar' => 'التعاون', 'price' => 5],
            ['id' => 395, 'zone_id' => 27, 'name' => 'Jalmudah', 'name_ar' => 'جلمودة', 'price' => 5],
            ['id' => 396, 'zone_id' => 27, 'name' => 'Qurtubah', 'name_ar' => 'قرطبة', 'price' => 5],
            ['id' => 397, 'zone_id' => 27, 'name' => 'Al Khaleej', 'name_ar' => 'الخليج', 'price' => 5],
            ['id' => 398, 'zone_id' => 27, 'name' => 'Abu Musa Al Ashari', 'name_ar' => 'ابو موسى الاشعري', 'price' => 5],
            ['id' => 399, 'zone_id' => 27, 'name' => 'Al Mutrafiyah', 'name_ar' => 'المطرفية', 'price' => 5],
            ['id' => 400, 'zone_id' => 28, 'name' => 'Al Mubarraz', 'name_ar' => 'المبرز', 'price' => 5],
            ['id' => 401, 'zone_id' => 28, 'name' => 'Al Mahasin', 'name_ar' => 'المحاسن', 'price' => 5],
            ['id' => 402, 'zone_id' => 28, 'name' => 'Al Muhassin', 'name_ar' => 'المحسن', 'price' => 5],
            ['id' => 403, 'zone_id' => 28, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 404, 'zone_id' => 28, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 405, 'zone_id' => 28, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 406, 'zone_id' => 28, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 407, 'zone_id' => 28, 'name' => 'Al Mazrouiyah', 'name_ar' => 'المزروعية', 'price' => 5],
            ['id' => 408, 'zone_id' => 28, 'name' => 'Al Bustan', 'name_ar' => 'البستان', 'price' => 5],
            ['id' => 409, 'zone_id' => 28, 'name' => 'Al Shabab', 'name_ar' => 'الشباب', 'price' => 5],
            ['id' => 410, 'zone_id' => 28, 'name' => 'Al Qadisiyah', 'name_ar' => 'القادسية', 'price' => 5],
            ['id' => 411, 'zone_id' => 28, 'name' => 'Al Jishah', 'name_ar' => 'الجشة', 'price' => 5],
            ['id' => 412, 'zone_id' => 28, 'name' => 'Al Bataliyah', 'name_ar' => 'البطالية', 'price' => 5],
            ['id' => 413, 'zone_id' => 29, 'name' => 'Al Qudaih', 'name_ar' => 'القديح', 'price' => 5],
            ['id' => 414, 'zone_id' => 29, 'name' => 'Al Safa', 'name_ar' => 'الصفا', 'price' => 5],
            ['id' => 415, 'zone_id' => 29, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 416, 'zone_id' => 29, 'name' => 'Al Jamiah', 'name_ar' => 'الجامعية', 'price' => 5],
            ['id' => 417, 'zone_id' => 29, 'name' => 'Al Bahari', 'name_ar' => 'البحاري', 'price' => 5],
            ['id' => 418, 'zone_id' => 29, 'name' => 'Al Awjam', 'name_ar' => 'الأوجام', 'price' => 5],
            ['id' => 419, 'zone_id' => 29, 'name' => 'Al Quds', 'name_ar' => 'القدس', 'price' => 5],
            ['id' => 420, 'zone_id' => 29, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 421, 'zone_id' => 29, 'name' => 'Al Zahra', 'name_ar' => 'الزهراء', 'price' => 5],
            ['id' => 422, 'zone_id' => 29, 'name' => 'Al Rabie', 'name_ar' => 'الربيع', 'price' => 5],
            ['id' => 423, 'zone_id' => 30, 'name' => 'Al Muftaha', 'name_ar' => 'المفتاحة', 'price' => 5],
            ['id' => 424, 'zone_id' => 30, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 425, 'zone_id' => 30, 'name' => 'Al Manhal', 'name_ar' => 'المنهل', 'price' => 5],
            ['id' => 426, 'zone_id' => 30, 'name' => 'Al Wardatayn', 'name_ar' => 'الوردتين', 'price' => 5],
            ['id' => 427, 'zone_id' => 30, 'name' => 'Al Shifa', 'name_ar' => 'الشفا', 'price' => 5],
            ['id' => 428, 'zone_id' => 30, 'name' => 'Al Mashhad', 'name_ar' => 'المشهد', 'price' => 5],
            ['id' => 429, 'zone_id' => 30, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 430, 'zone_id' => 30, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 431, 'zone_id' => 30, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 432, 'zone_id' => 30, 'name' => 'Al Andalus', 'name_ar' => 'الأندلس', 'price' => 5],
            ['id' => 433, 'zone_id' => 31, 'name' => 'Al Dhabab', 'name_ar' => 'الضباب', 'price' => 5],
            ['id' => 434, 'zone_id' => 31, 'name' => 'Al Raqi', 'name_ar' => 'الراقي', 'price' => 5],
            ['id' => 435, 'zone_id' => 31, 'name' => 'Al Qafilah', 'name_ar' => 'القافلة', 'price' => 5],
            ['id' => 436, 'zone_id' => 31, 'name' => 'Al Waha', 'name_ar' => 'الواحة', 'price' => 5],
            ['id' => 437, 'zone_id' => 31, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 438, 'zone_id' => 31, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 439, 'zone_id' => 31, 'name' => 'Al Nakhil', 'name_ar' => 'النخيل', 'price' => 5],
            ['id' => 440, 'zone_id' => 31, 'name' => 'Al Iskan', 'name_ar' => 'الإسكان', 'price' => 5],
            ['id' => 441, 'zone_id' => 31, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 442, 'zone_id' => 32, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 443, 'zone_id' => 32, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 444, 'zone_id' => 32, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 445, 'zone_id' => 32, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 446, 'zone_id' => 32, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 447, 'zone_id' => 33, 'name' => 'Al Murooj', 'name_ar' => 'المروج', 'price' => 5],
            ['id' => 448, 'zone_id' => 33, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 449, 'zone_id' => 33, 'name' => 'Al Sultanah', 'name_ar' => 'السلطانة', 'price' => 5],
            ['id' => 450, 'zone_id' => 33, 'name' => 'Al Muruj', 'name_ar' => 'المروج', 'price' => 5],
            ['id' => 451, 'zone_id' => 33, 'name' => 'Al Wurud', 'name_ar' => 'الورود', 'price' => 5],
            ['id' => 452, 'zone_id' => 33, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 453, 'zone_id' => 33, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 454, 'zone_id' => 33, 'name' => 'Al Qadisiyah', 'name_ar' => 'القادسية', 'price' => 5],
            ['id' => 455, 'zone_id' => 33, 'name' => 'Al Naseem', 'name_ar' => 'النسيم', 'price' => 5],
            ['id' => 456, 'zone_id' => 33, 'name' => 'Al Rajhi', 'name_ar' => 'الراجحي', 'price' => 5],
            ['id' => 457, 'zone_id' => 34, 'name' => 'Al Balad', 'name_ar' => 'البلد', 'price' => 5],
            ['id' => 458, 'zone_id' => 34, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 459, 'zone_id' => 34, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 460, 'zone_id' => 34, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 461, 'zone_id' => 35, 'name' => 'Al Balad', 'name_ar' => 'البلد', 'price' => 5],
            ['id' => 462, 'zone_id' => 35, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 463, 'zone_id' => 35, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 464, 'zone_id' => 35, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 465, 'zone_id' => 35, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 466, 'zone_id' => 36, 'name' => 'Al Naqrah', 'name_ar' => 'النقرة', 'price' => 5],
            ['id' => 467, 'zone_id' => 36, 'name' => 'Al Wusayta', 'name_ar' => 'الوسيطاء', 'price' => 5],
            ['id' => 468, 'zone_id' => 36, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 469, 'zone_id' => 36, 'name' => 'Al Khuzama', 'name_ar' => 'الخزامى', 'price' => 5],
            ['id' => 470, 'zone_id' => 36, 'name' => 'Al Muntazah', 'name_ar' => 'المنتزه', 'price' => 5],
            ['id' => 471, 'zone_id' => 36, 'name' => 'Al Sahafah', 'name_ar' => 'الصحافة', 'price' => 5],
            ['id' => 472, 'zone_id' => 36, 'name' => 'Al Mahatta', 'name_ar' => 'المحطة', 'price' => 5],
            ['id' => 473, 'zone_id' => 36, 'name' => 'Al Jamiyin', 'name_ar' => 'الجامعيين', 'price' => 5],
            ['id' => 474, 'zone_id' => 37, 'name' => 'Baqaa', 'name_ar' => 'بقعاء', 'price' => 5],
            ['id' => 475, 'zone_id' => 37, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 476, 'zone_id' => 37, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 477, 'zone_id' => 38, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 478, 'zone_id' => 38, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 479, 'zone_id' => 38, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 480, 'zone_id' => 38, 'name' => 'Al Muruj', 'name_ar' => 'المروج', 'price' => 5],
            ['id' => 481, 'zone_id' => 38, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 482, 'zone_id' => 39, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 483, 'zone_id' => 39, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 484, 'zone_id' => 39, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 485, 'zone_id' => 40, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 486, 'zone_id' => 40, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 487, 'zone_id' => 40, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 488, 'zone_id' => 41, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 489, 'zone_id' => 41, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 490, 'zone_id' => 41, 'name' => 'Al Safa', 'name_ar' => 'الصفا', 'price' => 5],
            ['id' => 491, 'zone_id' => 41, 'name' => 'Al Suways', 'name_ar' => 'السويس', 'price' => 5],
            ['id' => 492, 'zone_id' => 41, 'name' => 'Al Souq', 'name_ar' => 'السوق', 'price' => 5],
            ['id' => 493, 'zone_id' => 41, 'name' => 'Al Shamia', 'name_ar' => 'الشامية', 'price' => 5],
            ['id' => 494, 'zone_id' => 41, 'name' => 'Al Manhal', 'name_ar' => 'المنهل', 'price' => 5],
            ['id' => 495, 'zone_id' => 41, 'name' => 'Al Nakheel', 'name_ar' => 'النخيل', 'price' => 5],
            ['id' => 496, 'zone_id' => 42, 'name' => 'Sabya', 'name_ar' => 'صبيا', 'price' => 5],
            ['id' => 497, 'zone_id' => 42, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 498, 'zone_id' => 42, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 499, 'zone_id' => 42, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 500, 'zone_id' => 43, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 501, 'zone_id' => 43, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 502, 'zone_id' => 43, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 503, 'zone_id' => 43, 'name' => 'Al Shati', 'name_ar' => 'الشاطئ', 'price' => 5],
            ['id' => 504, 'zone_id' => 44, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 505, 'zone_id' => 44, 'name' => 'Al Makhayim', 'name_ar' => 'المخيم', 'price' => 5],
            ['id' => 506, 'zone_id' => 44, 'name' => 'Al Khalidiyah', 'name_ar' => 'الخالدية', 'price' => 5],
            ['id' => 507, 'zone_id' => 44, 'name' => 'Al Faysaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 508, 'zone_id' => 44, 'name' => 'Al Shorfa', 'name_ar' => 'الشرفة', 'price' => 5],
            ['id' => 509, 'zone_id' => 44, 'name' => 'Al Aba', 'name_ar' => 'العبا', 'price' => 5],
            ['id' => 510, 'zone_id' => 44, 'name' => 'Al Gharbi', 'name_ar' => 'الغربي', 'price' => 5],
            ['id' => 511, 'zone_id' => 45, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 512, 'zone_id' => 45, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 513, 'zone_id' => 45, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 514, 'zone_id' => 46, 'name' => 'Al Baha', 'name_ar' => 'الباحة', 'price' => 5],
            ['id' => 515, 'zone_id' => 46, 'name' => 'Al Hosn', 'name_ar' => 'الحصن', 'price' => 5],
            ['id' => 516, 'zone_id' => 46, 'name' => 'Al Zahra', 'name_ar' => 'الزهراء', 'price' => 5],
            ['id' => 517, 'zone_id' => 46, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 518, 'zone_id' => 46, 'name' => 'Al Shafa', 'name_ar' => 'الشفا', 'price' => 5],
            ['id' => 519, 'zone_id' => 47, 'name' => 'Baljurashi', 'name_ar' => 'بلجرشي', 'price' => 5],
            ['id' => 520, 'zone_id' => 47, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 521, 'zone_id' => 47, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 522, 'zone_id' => 47, 'name' => 'Al Shifa', 'name_ar' => 'الشفا', 'price' => 5],
            ['id' => 523, 'zone_id' => 48, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 524, 'zone_id' => 48, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 525, 'zone_id' => 48, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 526, 'zone_id' => 48, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 527, 'zone_id' => 48, 'name' => 'Al Nuzhah', 'name_ar' => 'النزهة', 'price' => 5],
            ['id' => 528, 'zone_id' => 49, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 529, 'zone_id' => 49, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 530, 'zone_id' => 49, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 531, 'zone_id' => 49, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 532, 'zone_id' => 50, 'name' => 'Al Safra', 'name_ar' => 'الصفراء', 'price' => 5],
            ['id' => 533, 'zone_id' => 50, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 534, 'zone_id' => 50, 'name' => 'Al Iskan', 'name_ar' => 'الإسكان', 'price' => 5],
            ['id' => 535, 'zone_id' => 50, 'name' => 'Al Muntazah', 'name_ar' => 'المنتزه', 'price' => 5],
            ['id' => 536, 'zone_id' => 50, 'name' => 'Al Rabwah', 'name_ar' => 'الربوة', 'price' => 5],
            ['id' => 537, 'zone_id' => 50, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 538, 'zone_id' => 50, 'name' => 'Al Nahdah', 'name_ar' => 'النهضة', 'price' => 5],
            ['id' => 539, 'zone_id' => 50, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 540, 'zone_id' => 51, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 541, 'zone_id' => 51, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 542, 'zone_id' => 51, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 543, 'zone_id' => 51, 'name' => 'Al Waha', 'name_ar' => 'الواحة', 'price' => 5],
            ['id' => 544, 'zone_id' => 51, 'name' => 'Al Matar', 'name_ar' => 'المطار', 'price' => 5],
            ['id' => 545, 'zone_id' => 51, 'name' => 'Al Iskan', 'name_ar' => 'الإسكان', 'price' => 5],
            ['id' => 546, 'zone_id' => 52, 'name' => 'Al Rayyan', 'name_ar' => 'الريان', 'price' => 5],
            ['id' => 547, 'zone_id' => 52, 'name' => 'Al Faisaliyah', 'name_ar' => 'الفيصلية', 'price' => 5],
            ['id' => 548, 'zone_id' => 52, 'name' => 'Al Rawdah', 'name_ar' => 'الروضة', 'price' => 5],
            ['id' => 549, 'zone_id' => 52, 'name' => 'Al Aziziyah', 'name_ar' => 'العزيزية', 'price' => 5],
            ['id' => 550, 'zone_id' => 52, 'name' => 'Al Iskan', 'name_ar' => 'الإسكان', 'price' => 5]
        ];
    }
}

